version: '3.6'

services:
  db:
    #platform: linux/x86_64 # for Mac M1 (ohne Plattform für Intel Macs)
    image: mysql:8.0.26
    ports:
      - 3306:3306
    volumes:
      - ./mysql_db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: nimda
      MYSQL_DATABASE: mashupdb
      MYSQL_USER: admin
      MYSQL_PASSWORD: nimda

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '8090:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: nimda
